"              __                                   
"             /  |                                  
"   __     __ $$/  _____  ____    ______    _______ 
"  /  \   /  |/  |/     \/    \  /      \  /       |
"  $$  \ /$$/ $$ |$$$$$$ $$$$  |/$$$$$$  |/$$$$$$$/ 
"   $$  /$$/  $$ |$$ | $$ | $$ |$$ |  $$/ $$ |      
"  __$$ $$/   $$ |$$ | $$ | $$ |$$ |      $$ \_____ 
" /  |$$$/    $$ |$$ | $$ | $$ |$$ |      $$       |
" $$/  $/     $$/ $$/  $$/  $$/ $$/        $$$$$$$/ 
"                                                 
" -----------   vim run commands file -------------
"
"

" help key-notation to define shortcuts

" set encoding
set encoding=utf-8

" fold
"" zM - all collapse
"" zR - all reveal
"" za - toggle
set foldmethod=indent

" enable clipboard share
set clipboard=unnamedplus

" editor config
syntax enable

" enable automatic indentation
set autoindent

" enable indentation based by language
set smartindent

" Set VIM to use 256 colors
set t_Co=256

" show existing tab with 4 spaces width
set tabstop=4

" when indenting with '>', use 4 spaces width
set shiftwidth=4

" On pressing tab, insert 4 spaces
set expandtab

" open vertical splits on right
set splitright

" open slip horizontal on below
set splitbelow

" enable horizontal scroll for big lines
set nowrap

" guide line to max 80 characters per line
set colorcolumn=80

" search on the fly
set incsearch

" show menu instead search by tab
set wildmenu


"# mappings
" copy to clipboard
vnoremap <silent><Leader>y "yy <Bar> :call system('xclip -sel clip', @y)<CR>

" navigate between buffers
"" buffer next default: Ctrl + O, but include lines too
nnoremap <F10> :bn<cr>
"" buffer previous default: Ctrl + I
nnoremap <F12> :bp<cr>

" navigate between tabs
nnoremap <Leader><Tab> :tabnext<CR>
nnoremap <Leader><S-Tab> :tabprevious<CR>

"reindent
map <F9> gg=G

"vimrc edit shortcut
nmap <Leader>vc :e $MYVIMRC<CR> 

" shortcut to save as
nnoremap <leader>sa :call SaveAsAndOpen()<CR>

"# auto commands
" auto 'reload' configs when save .vimrc
autocmd BufWritePost .vimrc source %


" functions
function! SaveAsAndOpen()
  let current_file = expand('%:p') " Get the full path of the current file
  let new_file = input("Save as: ", current_file)

  if new_file != "" && new_file != current_file
    execute "w " . fnameescape(new_file)
    execute "edit " . fnameescape(new_file)
  elseif new_file != ""
    echo "New file name is the same as the current file."
  endif
endfunction

" fix typos
command WQ wq
command Wq wq
command W w
command Q q
command QW wq
command Vsp vsp
command E e

